#!/bin/bash

# firewall.sh -- the documented firewall posture for this laptop, and a checker for it.
#
# THIS FILE IS NOT WHAT LOADS THE RULES. iptables.service runs
# /etc/systemd/scripts/iptables at boot, and that file's content is generated by
# ~/agent-built-lfs from a review decision in hosts/laptop/blfs-overrides.json
# (page blfs-iptables, block 2). Editing the installed script by hand gets the edit
# thrown away the next time that repo's bin/extract-blfs.py runs, and its own --check
# reports the edit as drift.
#
# What this file is for: one readable place where every rule sits next to the reason it
# exists, plus a `check` mode that tells me whether the running kernel still matches. It
# is deliberately a duplicate of the generated script. When they disagree, the generated
# one wins and this one is stale -- `./firewall.sh check` is how that gets noticed.
#
# usage:
#   ./firewall.sh            same as check
#   ./firewall.sh check      compare running kernel against what is documented here
#   ./firewall.sh show       print the documented posture, no root needed
#   ./firewall.sh apply --force
#                            flush and reload IPv4 filter from this file (see APPLY below)
#
# The old contents of this file (the pre-LFS Gentoo era) are folded in below as history
# and options, not dropped. The one piece of it worth keeping at the top is its own
# stated philosophy, which is still the posture:
#
#   "the gist is block all incoming, allow all outgoing
#    I used to restrict outbound and lost years to it..."
#
# APPLY, and why it is guarded. The reload sequence starts with `iptables -F; iptables -X`
# and `iptables -t nat -F`, which deletes chains this file does not own: tailscaled's
# ts-input, ts-forward and ts-postrouting, plus the jumps into them. Every tailnet
# connection to this box rides `INPUT -j ts-input`, so a flush cuts the tailnet until
# tailscaled reinstalls its own rules, which it does on its own schedule rather than
# immediately. apply therefore ends with `systemctl try-restart tailscaled`, which forces
# that reinstall. A one-off addition is better done with a single `iptables -A` and a
# matching edit here -- no flush, nothing else disturbed.

set -uo pipefail

# ---------------------------------------------------------------------------------
# Kernel tunables. Same list, same values, same order as the generated script.
# ---------------------------------------------------------------------------------
#
# icmp_echo_ignore_broadcasts  do not answer pings sent to a broadcast address
#                              (smurf amplification)
# accept_source_route          drop packets carrying a source route; nothing here
#                              legitimately sends one
# tcp_syncookies               survive a SYN flood without dropping the listen backlog
# accept_redirects             do not let an on-link host rewrite this box's routing
#                              table with an ICMP redirect
# send_redirects               this box is not a router, so it has no redirects to send
# rp_filter                    drop a packet whose source address is not reachable back
#                              out the interface it arrived on
# log_martians                 log impossible source addresses
# ip_dynaddr                   rebind sockets across a dynamic-IP change (DHCP wifi)
# tcp_ecn                      off; enough middleboxes still mishandle ECN to be a
#                              connectivity problem, not a performance one
declare -A SYSCTL=(
    [net.ipv4.icmp_echo_ignore_broadcasts]=1
    [net.ipv4.conf.all.accept_source_route]=0
    [net.ipv4.conf.default.accept_source_route]=0
    [net.ipv4.tcp_syncookies]=1
    [net.ipv4.conf.all.accept_redirects]=0
    [net.ipv4.conf.default.accept_redirects]=0
    [net.ipv4.conf.all.send_redirects]=0
    [net.ipv4.conf.default.send_redirects]=0
    [net.ipv4.conf.all.rp_filter]=1
    [net.ipv4.conf.default.rp_filter]=1
    [net.ipv4.conf.all.log_martians]=1
    [net.ipv4.conf.default.log_martians]=1
    [net.ipv4.ip_dynaddr]=2
    [net.ipv4.tcp_ecn]=0
)

# Two of those do not mean what the plain value suggests. Both were checked against this
# kernel's own source (/sources/linux-6.18.49, the running 6.18.49), not assumed:
#
# accept_redirects -- include/linux/inetdevice.h:126 IN_DEV_RX_REDIRECTS is `ANDCONF`
# when forwarding is on and `ORCONF` when it is off. ip_forward is 0 here, so it is the
# OR of conf/all and the per-interface value: whatever conf.all says goes, whatever the
# interfaces say. That is why `all` is in the list above and why it had to be added.
#
#   Found and fixed 2026-09-09. Until then the value was 1 -- the kernel's default,
#   never written -- so ICMP redirects were being accepted on every interface while
#   default=0 and eth0/wlp4s0/wg0/tailscale0=0 made the box look like it refused them.
#   The BLFS Personal Firewall example this box's script came from writes `default` and
#   never writes `all`, and `default` is only the template copied into interfaces
#   brought up later, so it cannot fix an interface that already exists. The book's
#   other example on the same page (Masquerading Router) does write `all`. Fixed in the
#   shared layer of ~/agent-built-lfs (recipes/blfs-overrides.json, blfs-iptables block
#   2) because it is true of any machine running that book, and pulled through
#   hosts/laptop/blfs-overrides.json as well, since a host block replaces the shared
#   block whole instead of adding to it.
#
#   Still 1 on lo, which is the kernel's default for loopback and is left alone: an ICMP
#   redirect cannot arrive on lo from off-box. Every routed interface reads 0.
#   secure_redirects=1 was never the answer -- it narrows acceptance to redirects from
#   an address that is already a default gateway, it does not refuse them.
#
# rp_filter -- inetdevice.h:103 IN_DEV_RPFILTER is MAXCONF, i.e. max(all, interface).
# all=1 and wg0=2 (wg-quick's own value), so wg0 runs in loose mode: the source only has
# to be reachable via *some* interface. Intended for the asymmetric-routing case a VPN
# creates; noted here so a future "why is rp_filter 2" does not turn into a hunt.

# ---------------------------------------------------------------------------------
# IPv4 filter rules, in the order they sit in the chains.
# ---------------------------------------------------------------------------------
# Policies: INPUT DROP, FORWARD DROP, OUTPUT DROP -- OUTPUT's DROP is then overridden by
# a blanket accept rule below, which is how the BLFS book's example is written. The
# effect is `-P OUTPUT ACCEPT`; the difference is that a flush without a reload leaves
# the box unable to talk instead of wide open.
POLICY_INPUT=DROP
POLICY_FORWARD=DROP
POLICY_OUTPUT=DROP

RULES=(
    # Local traffic. Needs to be first: tor on 127.0.0.1:9050 and resolved on
    # 127.0.0.53:53 are loopback-only listeners and everything on this box uses them.
    "INPUT -i lo -j ACCEPT"

    # Free outbound, per the philosophy quoted at the top. Paired with the DROP policy
    # above rather than replacing it.
    "OUTPUT -j ACCEPT"

    # Stateful return traffic. Every outbound connection's replies arrive here, as do
    # the related flows (ICMP errors, active-mode FTP data).
    "INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"

    # sshd. Not in the book's example, which opens nothing inbound at all -- applying it
    # unmodified would have locked out the only way in. Unscoped by source: this box gets
    # administered from the LAN, from the tailnet and over wireguard, and a source list
    # that is wrong at 2am locks out the only way in.
    #
    # What is behind it, from `sshd -T` after the 2026-09-09 change: PermitRootLogin no,
    # PubkeyAuthentication yes, PasswordAuthentication no, KbdInteractiveAuthentication
    # no. Keys only -- john's three authorized_keys (pi-tv, pi-master-tv, server); root
    # has no authorized_keys and no password path either.
    #
    # That change was already half-written and not working. /etc/ssh/sshd_config had
    # `PasswordAuthentication yes` at line 119 (the book's own text) and
    # `PasswordAuthentication no` appended at line 122, and sshd honours the FIRST
    # occurrence of a repeated directive, so `sshd -T` reported yes. Reading the tail of
    # that file would have told you passwords were off while sshd accepted them. The
    # blfs-openssh override now deletes the directive before appending it, which is the
    # same fix its PermitRootLogin line already carried.
    #
    # Still open, deliberately: tcp/22 is open to every interface, including public wifi.
    # Scoping it to the three administering subnets (192.168.0.0/24, 10.0.0.0/24,
    # 100.64.0.0/10) is the next step if wanted; a wrong source list locks out the only
    # way in, which is why it has not been done blind.
    "INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -j ACCEPT"

    # nginx, added 2026-09-09. Two matches, and both are load-bearing. -s 10.0.0.0/24 is
    # the wireguard subnet from /etc/wireguard/wg0.conf's Address= and the router peer's
    # AllowedIPs=. -i wg+ covers wg0 (split tunnel) and wg1 (full tunnel), which carry
    # the same address and are never up together. Without the interface match, the source
    # match is just a claim the sender makes about itself: a packet arriving on eth0 or
    # wlp4s0 with a forged 10.0.0.x source would match. With it, the LAN still has no
    # path to tcp/80 -- verified from the router, which reaches 10.0.0.2:80 over wg0 and
    # times out against 192.168.0.210:80.
    #
    # What is on the other side of this rule: nginx serves /mnt/crypt/john with
    # `autoindex on`, i.e. a browsable index of the whole home directory, so anyone
    # holding a peer key on the home router can read it. Recorded, not narrowed --
    # narrowing it is a docroot change to /mnt/crypt/john/web_server, not a firewall
    # change. See the OPERATOR DECISION header in
    # ~/agent-built-lfs/hosts/laptop/overlay/etc/nginx/nginx.conf.
    "INPUT -i wg+ -s 10.0.0.0/24 -p tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT"
)

# No LOG rule. The book's example logs every dropped packet, which on a box that spends
# its day on public wifi is a constant stream of scan noise. Drops are silent here; if
# something needs debugging, add a LOG rule temporarily, and see the broadcast/multicast
# option under HISTORY below, which only earns its place once a LOG rule exists.

# ---------------------------------------------------------------------------------
# Not ours: tailscaled -- and shields are up as of 2026-09-09
# ---------------------------------------------------------------------------------
# tailscaled installs and owns ts-input, ts-forward (filter) and ts-postrouting (nat),
# and the jumps into them from INPUT/FORWARD/POSTROUTING. They are not written here and
# not compared by check -- tailscaled rewrites them whenever it feels the need.
#
# `-A ts-input -i tailscale0 -j ACCEPT` is still in that chain and still accepts
# anything arriving over tailscale0, every port, ahead of every rule in this file. What
# changed is upstream of it: `tailscale set --shields-up` (ShieldsUp: true in
# `tailscale debug prefs`) makes tailscaled refuse inbound tailnet connections in its own
# userspace filter, so nothing gets injected into tailscale0 for a flow the tailnet
# starts. Return traffic for connections this box starts is unaffected -- verified by
# toggling it off and back on, which changed nothing about outbound. The setting lives in
# tailscaled's prefs, not in this file and not in the repo, and survives reboot.
#
# One claim corrected while doing this. The nginx.conf header and this file's earlier
# revisions both said every node on this tailnet can browse the docroot. Not
# demonstrable: `iptables -L ts-input -v` shows 13 packets total on the tailscale0 accept
# rule over four days of uptime, and an ssh from `server` to this box's tailnet address
# did not move that counter at all -- the packets never reached the kernel. So inbound
# was already being refused inside tailscaled (the tailnet's ACL policy), not by
# anything here. The tagged ifd-* devices were not testable from here, so the honest
# statement is narrower than the old one: this host's *firewall* imposes nothing on the
# tailnet, the enforcement was living in a policy someone can change in a web console,
# and shields-up moves it onto this device where it is visible.

# ---------------------------------------------------------------------------------
# IPv6: blocked entirely, 2026-09-09
# ---------------------------------------------------------------------------------
# Policy DROP on all three chains, flushed, with ::1 the only thing allowed. Before this
# ip6tables sat at policy ACCEPT with zero rules -- an unfiltered stack behind a filtered
# one -- because the book's script never touches ip6tables at all. What that exposed was
# bounded by this machine having no global v6 address (`ip -6 addr show scope global`
# empty, fe80 link-local only), but sshd listens on [::]:22, so it was reachable over
# link-local from the LAN with nothing in front of it.
#
# Verified after the change, from `server` on the same LAN segment: `ssh -6` to this
# box's fe80 address on port 22 times out, while the v4 control to the same sshd on the
# same run answers (publickey denial). Off-box v6 egress fails in ~1ms rather than
# hanging, because with no global address there is no route to hang on, and a dual-stack
# request (`curl https://example.com`) still completes in ~80ms.
#
# Total rather than a v4-style mirror: no ICMPv6, no neighbour discovery, no router
# advertisements. Nothing here needs v6 -- the WireGuard endpoint is v4, tailscale runs
# v4 on this host, no service requires it -- and blocking RA/NDP also means no v6 address
# ever gets configured, which is the point.
POLICY6_INPUT=DROP
POLICY6_FORWARD=DROP
POLICY6_OUTPUT=DROP

RULES6=(
    # ::1 only, and this is not a hole in the above. Software that resolves `localhost`
    # gets ::1 first here, and DROP gives a client nothing to fail on, so a dropped
    # loopback connection is a hang until it times out and retries 127.0.0.1 -- not a
    # clean failure. Blocking off-box v6 is the goal; making local sockets time out is
    # not. Delete these two if ::1 should die too.
    "INPUT -i lo -j ACCEPT"
    "OUTPUT -o lo -j ACCEPT"
)

# ---------------------------------------------------------------------------------
# HISTORY / OPTIONS -- from the pre-LFS version of this file, kept for the reasoning
# ---------------------------------------------------------------------------------
# None of these are applied. They are here because each one is a decision that was made
# once, and the reason it is off now is more useful than the rule itself.
#
# 1. Source-scoped ssh. The old file allowed tcp/22 from two hosts only:
#
#        iptables -A INPUT -s pi-tv        -p tcp --dport 22 -j ACCEPT
#        iptables -A INPUT -s pi-master-tv -p tcp --dport 22 -j ACCEPT
#
#    Off because the current rule is unscoped, for the reason given next to it. Also note
#    the shape: bare hostnames get resolved by iptables at load time, once, into whatever
#    address DNS said then. On a box whose LAN addresses come from DHCP that is a rule
#    that silently stops matching. If ssh ever does get scoped, scope it by subnet
#    (192.168.0.0/24, 10.0.0.0/24, 100.64.0.0/10) or by interface, not by hostname.
#
# 2. Source-scoped web. The old file's only inbound web rule was:
#
#        iptables -A INPUT -s android -p tcp --dport 80 -j ACCEPT
#
#    Same shape, same hostname problem, and worth noting that it is the same use case the
#    wireguard rule above now serves: reading the file server from the phone. The
#    wireguard version does it without depending on the phone's LAN lease and without
#    opening the port to the LAN at large.
#
# 3. Broadcast/multicast drop:
#
#        iptables -A INPUT -m addrtype --dst-type BROADCAST,MULTICAST -j DROP
#
#    The old comment was accurate about why it existed: "The box outputs several of them
#    when using netbios or mDNS, and those appear immediately as incoming, which clutters
#    the log." That payoff was against a LOG rule this file no longer has -- resolved's
#    mDNS/LLMNR traffic (5353, 5355) is already dropped by policy, silently. Turn this on
#    with a LOG rule, not before, and put it above the LOG rule.
#
# 4. `sudo` on every line. The old file ran each command through sudo so it could be
#    invoked as a user. This one asks for root once, in need_root, and re-execs.

# ---------------------------------------------------------------------------------

IPT=/usr/sbin/iptables
IP6T=/usr/sbin/ip6tables

need_root() {
    if [[ $EUID -ne 0 ]]; then
        exec sudo -- "$0" "$@"
    fi
}

show() {
    echo "documented posture (this file), not necessarily what is loaded:"
    echo
    echo "  sysctl"
    local k
    for k in "${!SYSCTL[@]}"; do
        printf "    %-45s = %s\n" "$k" "${SYSCTL[$k]}"
    done | sort
    echo
    echo "  iptables -P"
    printf "    %-8s %s\n" INPUT "$POLICY_INPUT" FORWARD "$POLICY_FORWARD" OUTPUT "$POLICY_OUTPUT"
    echo
    echo "  iptables -A"
    local r
    for r in "${RULES[@]}"; do
        echo "    $r"
    done
    echo
    echo "  ip6tables -P"
    printf "    %-8s %s\n" INPUT "$POLICY6_INPUT" FORWARD "$POLICY6_FORWARD" OUTPUT "$POLICY6_OUTPUT"
    echo
    echo "  ip6tables -A"
    for r in "${RULES6[@]}"; do
        echo "    $r"
    done
    echo
    echo "  tailscale: ShieldsUp expected true (inbound tailnet refused by tailscaled)"
    echo "  ts-input/ts-forward/ts-postrouting: owned by tailscaled, not checked"
}

# Presence of each documented rule is asked of the kernel with `iptables -C`, which
# normalises the spec the same way the kernel stores it -- so `-p tcp --dport 22` here
# matches the `-p tcp -m tcp --dport 22` that `iptables -S` prints back. The reverse
# direction (a live rule nobody documented) is reported as a count difference plus a dump
# of the live chains, not matched line by line; canonical-form comparison in shell is
# more trouble than it is worth for a five-rule ruleset.
check() {
    need_root check
    local fail=0 k live_val r spec live_rules doc_count live_count

    echo "== sysctl =="
    # Built into an array rather than piped straight into sort: a `for | sort` runs the
    # loop in a subshell, and fail=1 set in there never comes back out.
    local -a lines=()
    for k in "${!SYSCTL[@]}"; do
        live_val=$(sysctl -n "$k" 2>/dev/null)
        if [[ "$live_val" == "${SYSCTL[$k]}" ]]; then
            lines+=("$(printf "  ok      %-45s = %s" "$k" "$live_val")")
        else
            lines+=("$(printf "  DIFFERS %-45s = %s (documented %s)" \
                "$k" "${live_val:-unreadable}" "${SYSCTL[$k]}")")
            fail=1
        fi
    done
    printf '%s\n' "${lines[@]}" | sort -k2,2
    # Not in SYSCTL, reported because the comments above say why they matter.
    printf "  note    %-45s = %s (kernel default, inert: see accept_redirects comment)\n" \
        net.ipv4.conf.lo.accept_redirects "$(sysctl -n net.ipv4.conf.lo.accept_redirects)"
    printf "  note    %-45s = %s (wg-quick's, max() wins over all=1)\n" \
        net.ipv4.conf.wg0.rp_filter "$(sysctl -n net.ipv4.conf.wg0.rp_filter 2>/dev/null || echo 'no wg0')"

    echo "== policies =="
    for k in INPUT:$POLICY_INPUT FORWARD:$POLICY_FORWARD OUTPUT:$POLICY_OUTPUT; do
        live_val=$($IPT -S "${k%%:*}" | awk '/^-P/{print $3}')
        if [[ "$live_val" == "${k##*:}" ]]; then
            printf "  ok      %-8s %s\n" "${k%%:*}" "$live_val"
        else
            printf "  DIFFERS %-8s %s (documented %s)\n" "${k%%:*}" "$live_val" "${k##*:}"
            fail=1
        fi
    done

    echo "== rules =="
    for r in "${RULES[@]}"; do
        read -ra spec <<< "$r"
        if $IPT -C "${spec[@]}" 2>/dev/null; then
            printf "  ok      %s\n" "$r"
        else
            printf "  MISSING %s\n" "$r"
            fail=1
        fi
    done

    # Live rules in the three built-in chains, minus the jumps tailscaled owns.
    live_rules=$($IPT -S 2>/dev/null | grep -E '^-A (INPUT|FORWARD|OUTPUT) ' | grep -v -- '-j ts-')
    live_count=$(grep -c . <<< "${live_rules:-}")
    [[ -z "$live_rules" ]] && live_count=0
    doc_count=${#RULES[@]}
    if [[ "$live_count" -eq "$doc_count" ]]; then
        printf "  ok      %s live rule(s) outside tailscale's chains, %s documented\n" \
            "$live_count" "$doc_count"
    else
        printf "  DIFFERS %s live rule(s) outside tailscale's chains, %s documented:\n" \
            "$live_count" "$doc_count"
        sed 's/^/            /' <<< "$live_rules"
        fail=1
    fi

    echo "== ipv6 =="
    for k in INPUT:$POLICY6_INPUT FORWARD:$POLICY6_FORWARD OUTPUT:$POLICY6_OUTPUT; do
        live_val=$($IP6T -S "${k%%:*}" | awk '/^-P/{print $3}')
        if [[ "$live_val" == "${k##*:}" ]]; then
            printf "  ok      policy %-8s %s\n" "${k%%:*}" "$live_val"
        else
            printf "  DIFFERS policy %-8s %s (documented %s)\n" "${k%%:*}" "$live_val" "${k##*:}"
            fail=1
        fi
    done
    for r in "${RULES6[@]}"; do
        read -ra spec <<< "$r"
        if $IP6T -C "${spec[@]}" 2>/dev/null; then
            printf "  ok      %s\n" "$r"
        else
            printf "  MISSING %s\n" "$r"
            fail=1
        fi
    done
    live_count=$($IP6T -S | grep -c '^-A')
    if [[ "$live_count" -eq "${#RULES6[@]}" ]]; then
        printf "  ok      %s live v6 rule(s), %s documented\n" "$live_count" "${#RULES6[@]}"
    else
        printf "  DIFFERS %s live v6 rule(s), %s documented:\n" "$live_count" "${#RULES6[@]}"
        $IP6T -S | grep '^-A' | sed 's/^/            /'
        fail=1
    fi

    echo "== tailscale =="
    live_val=$(tailscale debug prefs 2>/dev/null | sed -n 's/.*"ShieldsUp": *\(true\|false\).*/\1/p')
    case "$live_val" in
        true)  printf "  ok      ShieldsUp true -- inbound tailnet connections refused by tailscaled\n" ;;
        false) printf "  DIFFERS ShieldsUp false -- the tailnet can open connections to this box\n"
               printf "          fix: sudo tailscale set --shields-up\n"; fail=1 ;;
        *)     printf "  note    ShieldsUp unreadable (tailscaled down?)\n" ;;
    esac

    echo "== not checked =="
    echo "  tailscale chains ($($IPT -S | grep -c '^-A ts-') rule(s) in ts-input/ts-forward)"

    if [[ $fail -eq 0 ]]; then
        echo
        echo "running kernel matches this file."
    else
        echo
        echo "running kernel does NOT match this file. The generated script"
        echo "(/etc/systemd/scripts/iptables, from ~/agent-built-lfs) is authoritative --"
        echo "diff against it before assuming the kernel is what is wrong."
    fi
    return $fail
}

apply() {
    need_root apply "$@"
    if [[ "${1:-}" != "--force" ]]; then
        echo "apply flushes the IPv4 filter and nat tables, which deletes tailscaled's" >&2
        echo "chains along with everything else, and reloads only what is in this file." >&2
        echo "This file is a copy of the generated script, not the source of it." >&2
        echo "Re-run with: $0 apply --force" >&2
        return 2
    fi

    local k
    for k in "${!SYSCTL[@]}"; do
        sysctl -qw "$k=${SYSCTL[$k]}"
    done

    modprobe nf_conntrack
    modprobe xt_LOG

    $IPT -P INPUT "$POLICY_INPUT"
    $IPT -P FORWARD "$POLICY_FORWARD"
    $IPT -P OUTPUT "$POLICY_OUTPUT"

    $IPT -F
    $IPT -X
    $IPT -Z
    $IPT -t nat -F

    local r spec
    for r in "${RULES[@]}"; do
        read -ra spec <<< "$r"
        $IPT -A "${spec[@]}"
    done

    $IP6T -P INPUT "$POLICY6_INPUT"
    $IP6T -P FORWARD "$POLICY6_FORWARD"
    $IP6T -P OUTPUT "$POLICY6_OUTPUT"
    $IP6T -F
    $IP6T -X
    $IP6T -Z
    for r in "${RULES6[@]}"; do
        read -ra spec <<< "$r"
        $IP6T -A "${spec[@]}"
    done

    # Puts back what the flush above took from tailscaled.
    if systemctl is-active --quiet tailscaled; then
        systemctl try-restart tailscaled
        echo "tailscaled restarted to reinstall its chains."
    fi

    echo "applied. $(check >/dev/null 2>&1 && echo 'check passes.' || echo 'check does NOT pass -- run: '"$0"' check')"
}

case "${1:-check}" in
    check)      check ;;
    show)       show ;;
    apply)      shift; apply "$@" ;;
    -h|--help)  sed -n '3,38p' "$0" | sed 's/^# \?//' ;;
    *)          echo "unknown mode: $1 (try: check, show, apply --force, --help)" >&2; exit 2 ;;
esac
